import Head from 'next/head'
import Header from '@/components/Header'
import { useEffect, useState } from 'react'
import Link from 'next/link';

export default function Home() {

  const [todos , setTodos] = useState([]);
  const [inpVal, setInpVal] = useState("");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main className='mt-5 pt-3'>
      <Header />
      <h2 className='text-center pt-3'>TODO APP</h2>
      <input className='d-block mx-auto text-center w-50 p-1 mt-4' type="text" placeholder='Add Todo' value={inpVal} onChange={(e)=>{setInpVal(e.target.value);}}/>
      <Link className="bg_btn mb-4" href='javascript:void(0)' onClick={()=>{
        setTodos([...todos , inpVal]);
        setInpVal("");
      }}>Add Todo</Link>
      {
        todos && todos.map((todo , index)=>{
          return <h5 className='text-center' key={index + 5}>{todo}</h5>
        })
      }
      </main>
    </>
  )
}
