import Head from 'next/head'
import Header from '@/components/Header'
import { useEffect, useState } from 'react'
import Link from 'next/link';

export default function Home() {

  const [todos , setTodos] = useState([]);
  const [inpVal, setInpVal] = useState("");

  const addTodos = (e)=>{
    e.preventDefault()
    if(inpVal.length > 0){
    setTodos([...todos , inpVal]);
    setInpVal("");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='mt-5 pt-3'>
      <Header />
      <h2 className='text-center pt-3'>TODO APP</h2>
      <input className='d-block mx-auto text-center w-50 p-1 mt-4' type="text" placeholder='Add Todo' value={inpVal} onChange={(e)=>{setInpVal(e.target.value);}}/>
      <Link className="bg_btn mb-4" href='#' onClick={addTodos}>Add Todo</Link>
      {
        todos && todos.map((todo , index)=>{
          return <h5 className='text-center' key={index + 5}>{index+1}. {todo} <i className="fa fa-solid fa-xmark ps-1 text-danger cursor-pointer" onClick={()=>{
            const filteredArray = todos.filter(e => e !== todos[index]);
            setTodos(filteredArray);
          }}></i></h5>
        })
      }
      </main>
    </>
  )
}
